name: Bug Report
description: Report a Esora bug
title: '[Bug]: '
labels: 'bug'
body:
  - type: checkboxes
    attributes:
      label: Preflight Checklist
      description: Please ensure you've completed all of the following.
      options:
        - label: I have read `CONTRIBUTING.md`
          required: true
        - label: I can reproduce this bug repeatedly.
          required: false
  - type: input
    attributes:
      label: Esora Version
      description: |
        What version of Esora are you using?
      placeholder: 0.0.1
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expect to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: If your question requires further explanation, or if you're experiencing a problem that cannot be easily reproduced, please add more information here.
